scriptencoding utf-8

"pathogen
call pathogen#infect()
call pathogen#helptags()

"General
syntax on
set nocompatible
set shell=/bin/bash
let mapleader=","
set encoding=utf-8
set tabstop=2
set shiftwidth=2
set expandtab
set virtualedit=all 
filetype on
filetype plugin on
filetype indent on
set lazyredraw
set synmaxcol=2048
set shellslash
set scrolloff=6
set sidescrolloff=6
set nowrap
set shortmess+=l
set hidden
set cursorline
set relativenumber
set number

"auto change directory on buffer switch
"autocmd BufEnter * cd %:p:h

"Show 80 character column
let &colorcolumn=join(range(80,900),",")

set fillchars=stl:.
set listchars=eol:¬,tab:▸\ ,trail:‧

"Search
set incsearch
set ignorecase
set smartcase
set hlsearch

"disable gui toolbar and scrollbars
set guioptions=acg
set mousehide

"colorsheme
let base16colorspace=256
set background=dark
colorscheme base16-tomorrow

"java highlighting
let java_highlight_java_lang_ids=1
let java_highlight_all=1
let java_highlight_functions="style"

"gradle highlighting
au BufNewFile,BufRead *.gradle setf groovy

"vimux
noremap <Leader>! :VimuxPromptCommand<CR>
noremap <Leader>rl :VimuxRunLastCommand<CR>
noremap <Leader>ri :VimuxInspectRunner<CR>
noremap <Leader>rx :VimuxClosePanes<CR>
noremap <Leader>rq :VimuxCloseRunner<CR>
noremap <Leader>rs :VimuxInterruptRunner<CR>

"UltiSnips
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"
let g:UltiSnipsExpandTrigger = '<c-l>'

"TagBar  https://github.com/majutsushi/tagbar
nnoremap <F8> :TagbarToggle<CR>

"eclimd
let g:EclimCompletionMethod = 'omnifunc'

"YouCompleteMe
let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/cpp/ycm/.ycm_extra_conf.py'

"Emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
